### ISSUE TITLE
User Reset Password Links in Email Don't Work

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#177] opened 2024-03-23 14:35 UTC
### Reproduction steps

When I:
- See log in screen
- Press" Forgot your password"
- Enter my email and submit

Issue 1: Email comes to my Junk Folder
Issue 2: None of the links in the email work to reset my password

### Expected behaviour

Should send me to the website to reset my password

### Screenshots / Videos

Reset Password

Follow this link to reset the password for your user:

[Reset Password](https://iqzrofvpvbklbirfkakw.supabase.co/auth/v1/verify?token=pkce_580e8c3dca3e7427e801cb023b6702071f1eff5051e13c2fdd7fbd23&type=recovery&redirect_to=http://localhost:3000)

Confirmation URL: https://iqzrofvpvbklbirfkakw.supabase.co/auth/v1/verify?token=pkce_580e8c3dca3e7427e801cb023b6702071f1eff5051e13c2fdd7fbd23&type=recovery&redirect_to=http://localhost:3000

Site URL: http://localhost:3000/

Redirect URL:

Token Hash: pkce_580e8c3dca3e7427e801cb023b6702071f1eff5051e13c2fdd7fbd23

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by rickaw** [comment] 2024-03-25 09:43
@dan-langridge Thanks for this. Looking into the issue where the reset link is pointing to localhost now.

As for the issue where the email goes to your junk folder, this seems to be a common issue with emails from Supabase, our backend service. Setting up the email with a custom SMTP provider with the foodbank domain would be a workaround, but this would probably be a lower priority for now.

**Comment by rickaw** [comment] 2024-03-25 15:03
## Developer Notes
This was caused by the redirect URL not being configured correctly.

**Comment by rickaw** [comment] 2024-03-25 15:04
@dan-langridge I have managed to fix password reset link issue and managed to reset my password on the live site. Would you be able to check on your side please?

**Comment by dan-langridge** [comment] 2024-03-25 17:55
@rickaw Still doesn't work for me. 
This time, the links do point to the live site, however all links in the email send you to the log in page, not a page where you can reset your password

Reset Password

Follow this link to reset the password for your user:

[Reset Password](https://iqzrofvpvbklbirfkakw.supabase.co/auth/v1/verify?token=pkce_9a04ff811bbd04786c724a44f0fd32667cb0492783a7dd4aa72aeb87&type=recovery&redirect_to=https://main.d3dkw68f839t0q.amplifyapp.com/auth/reset-password)

Confirmation URL: https://iqzrofvpvbklbirfkakw.supabase.co/auth/v1/verify?token=pkce_9a04ff811bbd04786c724a44f0fd32667cb0492783a7dd4aa72aeb87&type=recovery&redirect_to=https://main.d3dkw68f839t0q.amplifyapp.com/auth/reset-password

Site URL: https://main.d3dkw68f839t0q.amplifyapp.com/

Redirect URL:

Token Hash: pkce_9a04ff811bbd04786c724a44f0fd32667cb0492783a7dd4aa72aeb87

**Comment by dan-langridge** [comment] 2024-03-25 18:00
@rickaw I tried resetting my password again (clicking "Forgot Your Password") and entered a different email for a different user account and received the following error:

<img width="659" alt="Screenshot 2024-03-25 at 17 58 14" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/f2ca2eae-641e-47ef-b6a0-8d4850f66527">

**Comment by rickaw** [comment] 2024-03-26 09:08
> This time, the links do point to the live site, however all links in the email send you to the log in page, not a page where you can reset your password

Bizarre - the link seems like you should be able to click on the "Reset password" and should be prompted to update the password. For now I've updated the email template to make this clearer. I'll keep investigating why this is happening for you.

**Comment by rickaw** [comment] 2024-03-26 09:15
> @rickaw I tried resetting my password again (clicking "Forgot Your Password") and entered a different email for a different user account and received the following error:
> 
> <img alt="Screenshot 2024-03-25 at 17 58 14" width="659" src="https://private-user-images.githubusercontent.com/80202270/316604598-f2ca2eae-641e-47ef-b6a0-8d4850f66527.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDQyODMsIm5iZiI6MTcxMTQ0Mzk4MywicGF0aCI6Ii84MDIwMjI3MC8zMTY2MDQ1OTgtZjJjYTJlYWUtNjQxZS00N2VmLWI2YTAtOGQ0ODUwZjY2NTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA5MDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MDk3N2JkZTlkZTk2ZjJlOWU2MDZiZDZmYTk0OGU1NDlhOTVhNmE1NWJiMGJiYTZlNzk5MTEwZDMzOTNiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lwd4xfJG02iLvlsyXSOeRkWsS45HRtngLA99bgcTW4M">

We are on a free tier of the backend service Supabase with no custom SMTP server for emails, which means we're currently limited to 3 emails per hour. We could either set up a custom SMTP provider or upgrade to the Pro tier on Supabase to increase this limit.

**Comment by dan-langridge** [comment] 2024-03-26 09:19
OK thanks for the explanation of that error. Unlikely we’ll have loads of people trying to reset their password at once, however, could we amend the error message to help users if they see this message?

Email rate limit exceeded. 
Please contact admin for help
***@***.*** ***@***.***> 

Thanks
Dan

**Comment by rickaw** [comment] 2024-03-26 09:37
> Email rate limit exceeded.
> Please contact admin for help
> ***@***.*** ***@***.***>

What should these email addresses be? I'm happy to bake the email addresses into the code for now (or not mention the email addresses in the error message at all, if that's also acceptable).

**Comment by dan-langridge** [comment] 2024-03-26 10:01
Email rate limit exceeded.
Please contact admin for help
tech@lambethpartnership.foodbank.org.uk

(The GitHub reply to Issue via email stripped my email from the message haha)

**Comment by dan-langridge** [comment] 2024-03-26 10:03
Email rate limit exceeded.
Please contact admin for help
help@foodbankapp.org

**Comment by rickaw** [comment] 2024-03-26 10:09
Thanks, I've raised #193 for the new error message to be dealt with separately

**Comment by rickaw** [comment] 2024-03-26 14:20
Additional actions from us:
- Edit the password reset email to say that the link needs to be opened using the same machine and browser
- If the password reset link did not work as expected, we should take the user to an error page and explain that it did not succeed, and a likely reason why.

**Comment by dan-langridge** [comment] 2024-03-26 14:47
> * Does the password reset work for you if you request the password and visit the link using the same machine / browser? (Bear in mind each password reset link can only be used once)
Yes, i managed to get the password reset link to link by requesting the password of the account I was just logged in as.
If I was logged in with Account A, logged out, and requested a password reset for Account B it would fail.


> * Do you think it will be a problem to ask volunteers to use their own device to reset their passwords?
I see this being a problem In the warehouse where we have dedicated laptops for tasks (Label Printing Laptops, Manager Laptop, etc) which different users log on to every day using their own account, and those laptops won't have email access.

**Comment by rickaw** [comment] 2024-03-26 15:48
> Warehouse users will be using a shared laptop, and if need to reset their password, will open their email on their phone to get the password reset link and open that link on their phone, so this won't work. I have just tested this and can confirm it currently doesn't work.

@dan-langridge Sorry I should have been clearer - the user will need to request the password reset link and visit the link, **both on their own phone**. (I was able to do test this earlier)

**Comment by rickaw** [comment] 2024-03-26 15:53
> If I was logged in with Account A, logged out, and requested a password reset for Account B it would fail. So for shared machines this will cause issues.

I was able to update my password for Account B successfully in this scenario. One possible reason for failure might be that you may be logged in with Account A on a different tab (this wouldn't be an issue if the user can request a password reset and follow the link all on their own phone).

**Comment by dan-langridge** [comment] 2024-03-26 15:59
> > Warehouse users will be using a shared laptop, and if need to reset their password, will open their email on their phone to get the password reset link and open that link on their phone, so this won't work. I have just tested this and can confirm it currently doesn't work.
> 
> @dan-langridge Sorry I should have been clearer - the user will need to request the password reset link and visit the link, **both on their own phone**. (I was able to do test this earlier) Do you think this will be a problem?

I think it's not the best solution but happy to go with it and see if it becomes a big issue

**Comment by rickaw** [comment] 2024-03-26 16:04
Sure, closing this issue for now. The additional actions that came out of this is covered in #199. Thanks for your patience on this one!

**Closed** 2024-03-26 16:05 UTC
Labels: bug
